- lib/sambal.rb
there might be some optional output from smbclient before showing the
prompt
e.g.:
Domain=[EU] OS=[Windows 5.0] Server=[Windows 2000 LAN Manager]
smb: \>
the expect statement in the connection code looks only for the prompt.
> there might be some optional output from smbclient before the prompt

- README.md
- lib/sambal.rb
- spec/spec_helper.rb
Hi there --
Really just two small changes:
1. Update the call to smbclient with quotation marks around parameters to support shares or usernames with spaces in them.
2. Fix a mistake in the README that refers to client.delete whereas it should be client.del
Also made a small change to spec_helper - config.color_enabled has been changed to config.color in the latest version of rspec (3.0.0).
Cheers,
Mike.
> Fix logins shares with spaces

- lib/sambal.rb
I found I was getting timeouts when copying large files across the network (1-2GB in size), so I added a timeout option to the initializer (defaults to 10 still).
> Added timeout option to initializer to permit wait longer than 10s

- lib/sambal.rb
- spec/sambal/client_spec.rb
Hi,
In most of the Rails apps file paths are being wrapped in a `Pathname`. Here's a quick fix to avoid explicit conversion to string on calling `get`, `put`, etc.
P.S. Also noticed a typo in one of the existing tests, fixed.
> Pathname support

- lib/sambal.rb
- spec/sambal/client_spec.rb
mkdir takes in a single argument which is the name of the directory to be created. Directory should have valid characters and spaces are handled accordingly. Added related tests to spec.
```ruby
@sambal.mkdir('test').success? # => true
@sambal.cd('test')
@sambal.mkdir('test folder spaces').sucess? # => true
@sambal_mkdir('test folder spaces')
@sambal.mkdir('*invalid*').success? #  => false
```
> Add mkdir method and associated tests

- lib/sambal/client.rb
PTY terminal has restriction of columns length (default = 80 charters) by each command row. So after row has more than 80 characters terminal switch to new line (set special symbols) and method 'getc' in IO.expect method can not read these "special symbols' from terminal
> fix working with long(then more 80 charters) path of folders/files

- lib/sambal/client.rb
> Rewrite parse_ls to tolerate file names with double spaces

- lib/sambal/client.rb
We ran into an issue recently where this library is using the top level `Exception` class instead of the lower-level `StandardError`. If you rescue exception, you also rescue issues like out of memory, SIGTERM, and other things that should rarely be rescued. This also means that the standard
```ruby
begin
rescue => e
end
```
doesn't capture exceptions emitted by this application.
This PR switches to using `StandardError`/`RuntimeError`, which keeps things cleaner for consuming applications.
Thanks!
> Use cleaner exception handling

- lib/sambal/client.rb
A library should never exit the ruby process.
> Don't exit on failure, raise an error

- lib/sambal/client.rb
- spec/sambal/client_spec.rb
Replacement for #33 with specs added and a small bug fixed in the error code path. Thanks to @manoktsina for the original work!
Adds the ability to rename files on the remote share.
> Ability to rename remote files

- lib/sambal/client.rb
New options:
--authentication-file
--send-buffer
--debuglevel
--encrypt
--max-protocol
--use-ccache
--socket-options
--name-resolve
--configfile
Also replaced short option names to readable equivalent
I wanted to write tests but it's not trivial (need refactor).
In commit there one assumption:
if user set `:authfile` option, then `:user`, `:password` and `:domain` should not be used (and will be ignored).
Not sure that it right but better solution also need big refactor
> Support of missed `smbclient` options

- lib/sambal/client.rb
Steps to reproduce the bug:
```ruby
smb_client = Sambal::Client.new # supply connection args here
smb_client.ls('test%20file.wav')
```
When the first argument to `IO#printf` (in this case, a command string containing a filename) contains a `%` character, `printf` expects additional arguments to supply data to the `%`-encoded fields of the first argument. Sambal is not passing a `%`-formatted string or data field args, so this branch replaces `printf` with `print`.
> Fix printf bug with filenames containing '%'

- lib/sambal/client.rb
I accessed file on the samba then I got following error, 
` Failed to do get #{filename}`
sambal should display more information for this errors.
> show original error when executing command

- sambal.gemspec
Do not rely on 'git' to list files.  It should be used Dir.glob instead.
There is a problem in the following cases
* when using package downloaded from GitHub as an archive(like tar.gz, zip)
* when not installed .git environment
ref: 
https://github.com/bundler/bundler/issues/6281
https://www.codinginthecrease.com/news_article/show/350843-using-git-in-your-gemspec
> Dir.glob instead of git ls-files

- lib/sambal/client.rb
Currently, Sambal does not work if smbclient is installed to a local path NOT including in $PATH.
This pull request adds an option to set the call path of smbclient.
> add "smbclient command" to option to use call from a custom path

- lib/sambal/client.rb
- spec/sambal/client_spec.rb
I made filename as sanitized that removes non printable chars and double quotes.
This PR prevents smb command injection by malicious filename.
> Prevent smb command injection

- lib/sambal/client.rb
- spec/sambal/client_spec.rb
I change command line construction from string concatenation to using array.
This PR prevents command injection by malicias flags.
> Prevent command injection

- .gitignore
- lib/sambal/client.rb
When trying to cd to a non existing directory, the version of smbclient I use responds with NT_STATUS_OBJECT_PATH_NOT_FOUND , the client#cd method tries to find the string NT_STATUS_OBJECT_NAME_NOT_FOUND , with this pull requests both strings are interpreted  as a non existing directory.
> Parse both NT_STATUS_OBJECT_NAME_NOT_FOUND and NT_STATUS_OBJECT_PATH_NOT_FOUND response from smbclient as non-existing directory

- lib/sambal/client.rb
The start of the string assertion can drop some successful responses.
As an example, my 'put' responses look like this:
`" put \"/some-long- \rpath\" \"/some-long- \rpath\"\r\n\e[?2004l\rputting file  /some-long-path as \\ \some-long-path (2755.5 kb/s) (average 2691.5 kb/s)\r\n\e[?2004hsmb: \\>"`
Even if the string was to be `.split("\n") `, it doesn't guarantee the assertion.
> no start of the string match for responses

- lib/sambal/client.rb
A small but important change for our use case of sambal.
The -k/--kerberos option for smbclient is deprecated, instead the --use-kerberos=desired|required|off should be used.
> Use the new --use-kerberos option for smbclient
